In [17]:
import matplotlib.pyplot as plt
import pandas as pd

df = pd.read_csv("train.csv")

In [18]:
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [19]:
# Check for missing values in each column
missing_values = df.isnull().sum().sort_values(ascending=False)

# Filter out the columns that have missing values
missing_values = missing_values[missing_values > 0]

missing_values

PoolQC          1453
MiscFeature     1406
Alley           1369
Fence           1179
FireplaceQu      690
LotFrontage      259
GarageYrBlt       81
GarageCond        81
GarageType        81
GarageFinish      81
GarageQual        81
BsmtFinType2      38
BsmtExposure      38
BsmtQual          37
BsmtCond          37
BsmtFinType1      37
MasVnrArea         8
MasVnrType         8
Electrical         1
dtype: int64

In [24]:
# Define the columns to drop
columns_to_drop = ['PoolQC', 'MiscFeature', 'Alley', 'Fence', 'FireplaceQu', 'LotFrontage', 
                   'GarageYrBlt', 'GarageCond', 'GarageType', 'GarageFinish', 'GarageQual', 
                   'BsmtFinType2', 'BsmtExposure', 'BsmtQual', 'BsmtCond', 'BsmtFinType1', 
                   'MasVnrArea', 'MasVnrType', 'Electrical']

# Drop the columns
df = df.drop(columns=columns_to_drop)
df.head()

,Id,MSSubClass,MSZoning,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,...,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,8450,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,0,2,2008,WD,Normal,208500
1,2,20,RL,9600,Pave,Reg,Lvl,AllPub,FR2,Gtl,...,0,0,0,0,0,5,2007,WD,Normal,181500
2,3,60,RL,11250,Pave,IR1,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,0,9,2008,WD,Normal,223500
3,4,70,RL,9550,Pave,IR1,Lvl,AllPub,Corner,Gtl,...,272,0,0,0,0,2,2006,WD,Abnorml,140000
4,5,60,RL,14260,Pave,IR1,Lvl,AllPub,FR2,Gtl,...,0,0,0,0,0,12,2008,WD,Normal,250000

In [ ]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline
from sklearn.ensemble import RandomForestRegressor

# Identify the categorical columns
categorical_columns = df.select_dtypes(include=['object']).columns

# Apply one-hot encoding to the categorical columns
preprocessor = make_column_transformer(
    (OneHotEncoder(handle_unknown='ignore'), categorical_columns),
    remainder='passthrough'
)

# Define the target variable
y = df['SalePrice']

# Define the feature set
X = df.drop(columns=['SalePrice'])

# Create a pipeline that first one-hot encodes the data and then applies RFE
model = make_pipeline(
    preprocessor,
    RFE(estimator=RandomForestRegressor(), n_features_to_select=20)
)

# Fit the model
model.fit(X, y)

# Get the feature ranking
ranking = model.named_steps['rfe'].ranking_

# Get the names of the columns after one-hot encoding
feature_names = model.named_steps['columntransformer'].get_feature_names_out()

# Create a DataFrame that associates each feature with its ranking
features_rfe = pd.DataFrame({'Feature': feature_names, 'Ranking': ranking})

# Show the top 10 features
top_features_rfe = features_rfe[features_rfe.Ranking == 1]
top_features_rfe

In [47]:


# Use the fitted model to transform the feature set
X = df.drop(columns=['SalePrice'])

X_transformed = model_rfe.transform(X)


# Train a random forest model using the transformed feature set

rf = RandomForestRegressor(n_estimators=100, random_state=4002)

rf.fit(X_transformed, y)



rf

RandomForestRegressor(random_state=4002)

In [64]:
# Load the new test dataset
test_df = pd.read_csv('test.csv')

# Select the same features as in the training set
test_X = test_df

test_X_puro = test_X.drop(columns=columns_to_drop)
test_X_filled = test_X_puro.fillna(0)


# Use the RFE model to transform the imputed test feature set
test_X_transformed = model_rfe.transform(test_X_filled)

# Use the trained random forest model to make predictions on the test set
test_y_pred = rf.predict(test_X_transformed)

# Create a DataFrame with the IDs and the predicted prices
predictions_df = pd.DataFrame({
    'Id': test_df['Id'],
    'SalePrice': test_y_pred
})

predictions_df.head()

     Id      SalePrice
0  1461  129861.496874
1  1462  145281.771530
2  1463  152687.666662
3  1464  182810.324742
4  1465  186421.357143

In [61]:
b= test_X_puro.isnull().sum().sort_values(ascending=False)

# Filter out the columns that have missing values
missing_values2 = b[b > 0]

missing_values2

MSZoning        4
Functional      2
BsmtFullBath    2
BsmtHalfBath    2
Utilities       2
BsmtFinSF2      1
BsmtFinSF1      1
Exterior2nd     1
GarageCars      1
GarageArea      1
Exterior1st     1
KitchenQual     1
BsmtUnfSF       1
TotalBsmtSF     1
SaleType        1
dtype: int64

In [60]:
a= X.isnull().sum().sort_values(ascending=False)

# Filter out the columns that have missing values
missing_values23 = a[a > 0]

missing_values23

Series([], dtype: int64)